-- 1. Create Assets Table
create table if not exists assets (
  id bigint generated by default as identity primary key,
  name text not null,
  symbol text not null unique,
  api_id text not null,
  icon_url text,
  location text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Transactions Table
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  date timestamp with time zone not null,
  type text not null check (type in ('Buy', 'Sell', 'Transfer', 'Airdrop', 'Staking Reward', 'Interest', 'Gift')),
  asset_id bigint references assets(id) not null,
  quantity numeric not null,
  price_per_unit numeric not null,
  total_amount numeric not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Portfolio Snapshots Table
create table if not exists portfolio_snapshots (
  id bigint generated by default as identity primary key,
  date date not null unique,
  total_value_jpy numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS (Row Level Security) - Optional but recommended
-- For now, allowing public access since we are just moving files
alter table assets enable row level security;
alter table transactions enable row level security;
alter table portfolio_snapshots enable row level security;

-- Create policies to allow everything for anon (since the app uses anon key)
create policy "Enable all for anon" on assets for all using (true) with check (true);
create policy "Enable all for anon" on transactions for all using (true) with check (true);
create policy "Enable all for anon" on portfolio_snapshots for all using (true) with check (true);

-- 5. Create Price Cache Table (for API rate limit fallback)
create table if not exists price_cache (
  api_id text primary key,
  price_usd numeric,
  price_jpy numeric,
  usd_24h_change numeric,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table price_cache enable row level security;
create policy "Enable all for anon" on price_cache for all using (true) with check (true);

-- 6. Storage Bucket (You must do this manually in Dashboard usually, but here is SQL if supported)
-- insert into storage.buckets (id, name, public) values ('images', 'images', true);
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'images' );
-- create policy "Anon Upload" on storage.objects for insert with check ( bucket_id = 'images' );

-- 7. AI Comments Table (Gemini daily insights)
create table if not exists ai_comments (
  id bigint generated by default as identity primary key,
  date date not null unique,
  comment text not null,
  portfolio_summary jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table ai_comments enable row level security;
create policy "Enable all for anon" on ai_comments for all using (true) with check (true);
